plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tododroid'
    compileSdk 33

    defaultConfig {
        applicationId "com.tododroid"
        minSdk 21
        targetSdk 33
        versionCode 3
        versionName "2.3"
    }

    signingConfigs {
        release {
            storeFile file("../tododroid-release.keystore")
            storePassword "tododroid123"
            keyAlias "tododroid"
            keyPassword "tododroid123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.code.gson:gson:2.10.1'
}
